database_migration_dir: migrations
database_table: schema_version
database_type: postgres
database_host: localhost
database_port: 5433
database_name: ghastly
database_username: ghastly
database_password: ghastly
